### ISSUE TITLE
An extra " char

### ISSUE THREAD

**Issue by panzerdp** [signalwerk/gatsby-remark-table-of-contents#1]
Thanks for creating this plugin!

I've noticed a typo in the wrapper div of table of contents:

```javascript
markdownAST.children = [].concat(
    markdownAST.children.slice(0, index),
    {
      type: 'html',
      value: '<div class="toc">',
    },
    result.map,
    {
      type: 'html',
      value: '</div">',  // <----------------- Remove "
    },
    markdownAST.children.slice(index + 1)
  );
```

You should remove `"` from the closing div: `</div">`.

**Comment by signalwerk** [comment]
thank you for the report and the nice words! I just fixed this. Thank you for the finding!

**Comment by signalwerk** [comment]
Version 0.0.8 should do the trick.
