### ISSUE TITLE
  Error: Unable to find plugin "gatsby-remark-table-of-contents".

### ISSUE THREAD

**Issue by jipiboily** [signalwerk/gatsby-remark-table-of-contents#17]
Hey folks,

So, I've followed the instructions from the README, (at least, AFAIK), but I am getting this error: 

```
/Users/jp/code/metricswatch.com-2019 (git)-[add-table-of-content] -> gatsby develop --verbose
verbose 0.579111075 set gatsby_log_level: "verbose"
verbose 0.581312298 set gatsby_executing_command: "develop"
verbose 0.582342348 loading local command from: /Users/jp/code/metricswatch.com-2019/node_modules/gatsby/dist/commands/develop.js
verbose 4.189184275 running command: develop
success open and validate gatsby-configs - 0.056s
⠋ load plugins


  Error: Unable to find plugin "gatsby-remark-table-of-contents". Perhaps you need to install its package?

  - load.js:109 resolvePlugin
    [metricswatch.com-2019]/[gatsby]/dist/bootstrap/load-plugins/load.js:109:11

  - load.js:153 processPlugin
    [metricswatch.com-2019]/[gatsby]/dist/bootstrap/load-plugins/load.js:153:20

  - load.js:134
    [metricswatch.com-2019]/[gatsby]/dist/bootstrap/load-plugins/load.js:134:27

  - Array.forEach

  - load.js:133 processPlugin
    [metricswatch.com-2019]/[gatsby]/dist/bootstrap/load-plugins/load.js:133:32

  - load.js:172
    [metricswatch.com-2019]/[gatsby]/dist/bootstrap/load-plugins/load.js:172:20

  - Array.forEach

  - load.js:171 module.exports
    [metricswatch.com-2019]/[gatsby]/dist/bootstrap/load-plugins/load.js:171:20

  - index.js:55 module.exports
    [metricswatch.com-2019]/[gatsby]/dist/bootstrap/load-plugins/index.js:55:19

  - index.js:167 module.exports
    [metricswatch.com-2019]/[gatsby]/dist/bootstrap/index.js:167:34

  - develop.js:401 async module.exports
    [metricswatch.com-2019]/[gatsby]/dist/commands/develop.js:401:7


⠋ load plugins
```

Yes, I did install the package, and the `gatsby-remark-autolink-headers` too. Although, the `gatsby-remark-autolink-headers` was originally the 3.0.0 version, but as I am not (yet) on Gatsby 3, I downgraded to the latest of 2.x.

I am using Gatsby 2.17.1 right now.

Are there known issues? How could I debug that?

**Comment by OfficePop** [comment]
Did you get a resolution on this issue? I am running into the same problem following the readme directions running gatsby 2.15.6 and autolink headers 4.4.1. Worth mentioning autolink works fine by itself.

**Comment by jipiboily** [comment]
Hey, my context changed: someone here did the work to upgrade Gatsby 3 on our end, so we were able to move forward and not get this issue.

So, for us, upgrading to Gatsby 3 was the path to success.

**Comment by signalwerk** [comment]
Thank you @jipiboily for your bug-report. Please excuse the delayed response. From what I read, you were able to solve the problem. the lates verison of this plugin should support Gatsby v3 and v4. Please don't hesitate to open the issue again if you need something else.
