### ISSUE TITLE
Use <ol> element instead of <ul>

### ISSUE THREAD

**Issue by dimitrisraptis96** [signalwerk/gatsby-remark-table-of-contents#8]
Hi! 
Thanks for this plugin. It's really handy for long blog posts. 

While using your plugin, I had the need to change the root element of your toc markdown component from `<ul>` to `<ol>`.

Is this functionality somehow supported?

**Comment by signalwerk** [comment]
Would be nice to set it in the options. If you feel like send me a pull request.

**Comment by thomasjungblut** [comment]
@signalwerk any hints on how to do it? Seems to be in `mdast-util-toc` [somewhat hardcoded](https://github.com/syntax-tree/mdast-util-toc/blob/342d4bd2653760580c1baccb5580fab92828c2d6/lib/contents.js#L9).

**Comment by signalwerk** [comment]
@thomasjungblut thank you for taking on that challenge and already have a look where to start. I think it would make sense to have an additional Option in [mdast-util-toc](https://github.com/syntax-tree/mdast-util-toc) `options.ordered`. So if you could add an option to the  [mdast-util-toc](https://github.com/syntax-tree/mdast-util-toc) we could pass on these options. Or what do you think would make sense?

**Comment by signalwerk** [comment]
@thomasjungblut awesome! love your [PR](https://github.com/syntax-tree/mdast-util-toc/pull/69) Thank you for your effort!

**Comment by thomasjungblut** [comment]
@signalwerk let me know when you find the time to review #10 :)

**Comment by signalwerk** [comment]
🥳 super awesome. this is available from v0.2.0 on. I added now a new bundler (rollup) and some tests to have everything properly together. I also added you in the `readme.md`
